### PR TITLE
Removing kitchen sink app and fixing router link

### LINKED ISSUE #97: Routes demo should be using binding instead of string
Use binding instead of string on this line: 
https://github.com/rangle/augury-examples/blob/master/src/app/shared/header/header.component.html#L13

change:
`routerLink="item.routerLinkPath"`

to 
`[routerLink]="item.routerLinkPath"`

### PR DESCRIPTION
**Pull request by sumitarora**
closes #97

### CODE REVIEW

File: src/app/routes/base/base.component.ts [hunk 1]
```diff
@@ -1,41 +1,40 @@
...
+import { Component } from "@angular/core";
+import { NavItem } from "src/app/shared/nav-item";
 
 @Component({
-  selector: 'app-routes-root',
-  templateUrl: './base.component.html',
-  styleUrls: ['./base.component.css']
+  selector: "app-routes-root",
+  templateUrl: "./base.component.html",
+  styleUrls: ["./base.component.css"]
```
Comment (feeloor) [inline src/app/routes/base/base.component.ts]: Could we use single quotation marks instead? Should we potentially add `prettier` to this repo?

Comment (yallen011) [reply src/app/routes/base/base.component.ts]: Agreed, should be single quotes. Also the tslinter should catch that at compile time. It's a good one to have installed.

**Comment by feeloor** [comment]
closes #97
